config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :team, only: [:show, :update, :edit]

  resources :users, only: [:index, :show, :update] do
    # get :statuses, on: :member
  end

  resources :hashtags, only: [:index, :show] do
    # get :statuses, on: :member
    resource :like, only: [:create, :destroy]
  end

  resources :statuses, except: [:show] do
    collection do
      get :today
      get :yesterday
      constraints year: /\d{4}/, month: /(0?[1-9]|1[012])/, day: /(0?[1-9]|[12]\d|3[01])/ do
        get "/:year/:month/:day", action: :daily, as: :daily
        get "/:year/:month", action: :monthly, as: :monthly
        get "/:year", action: :yearly, as: :yearly
      end
    end
    resource :like, only: [:create, :destroy]
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  helper_method :users, :statuses

  def index
    @statuses = current_user.team.statuses.order(created_at: :desc).page(params[:page])
  end

  def new
    @status = current_user.statuses.build
  end

  def edit
  end

  def create
    @status = current_user.statuses.build(status_params)

    if @status.save
      redirect_to statuses_url, notice: "Status was successfully created."
    else
      render :new
    end
  end

  def update
    @status.photo = nil if params[:remove_status_photo] == "true"
    if @status.update(status_params)
      redirect_to statuses_url, notice: "Status was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @status.destroy
    redirect_to statuses_url, notice: "Status was successfully destroyed."
  end

  def today
    @period = Time.zone.today.beginning_of_day.all_day
  end

  def yesterday
    @period = Time.zone.yesterday.beginning_of_day.all_day
  end

  def daily
    @date = Time.zone.local(params[:year], params[:month], params[:day]).to_date
    @prev = @date.yesterday
    @next = @date.tomorrow
    @period = @date
  end

  def monthly
    @date = Time.zone.local(params[:year], params[:month]).to_date
    @prev = @date.prev_month
    @next = @date.next_month
    @period = @date.all_month
  end

  def yearly
    @date = Time.zone.local(params[:year]).to_date
    @prev = @date.prev_year
    @next = @date.next_year
    @period = @date.all_year
  end

  private

  def set_status
    @status = Status.find(params[:id])
  end

  def users
    @users ||= current_user.team.users
  end

  def statuses
    @statuses ||= current_user.team.statuses.during(@period).order(created_at: :desc).page(params[:page])
  end

  def status_params
    params.require(:status).permit(:description, :user_id, :photo)
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.slim
= simple_form_for(@status) do |f|
  = f.error_notification

  .form-inputs
    = f.input :description
    .status-photo
      - if @status.photo?
        = image_tag @status.photo.url(:thumb)
        = label_tag 'remove_status_photo' do
          = check_box_tag 'remove_status_photo', true, false
          = 'Remove Photo'
      = f.input :photo

  .form-actions
    = f.button :submit

app/views/statuses/_like.html.slim
= form_for(status, url: status_like_path(status), html: { method: :post},  remote: true) do |f|
  .form-actions
    = f.button 'Like', class: 'btn btn-link'

app/views/statuses/_status.html.slim
.status
  p.description == auto_link_hashtags status.description
  span.name => status.user.name
  => timeago_tag status.created_at
  ' ·
  span.likes-count data={ status_id: status.id } => pluralize status.likes_count, 'like'
  - if status.user_id == current_user.id
    ' ·
    = link_to 'edit', edit_status_path(status)
  - if status.photo?
    .status-photo
      = image_tag status.photo.url(:thumb)
  .like-form data={ status_id: status.id }
    - if current_user.likes?(status)
      == render 'statuses/unlike', status: status
    - else
      == render 'statuses/like', status: status

app/views/statuses/_unlike.html.slim
= form_for(status, url: status_like_path(status), html: { method: :delete }, remote: true) do |f|
  .form-actions
    = f.button 'Unlike', class: 'btn btn-link'

app/views/statuses/_users.html.slim
.active-people
  span.meta = pluralize users.active(@period).count, "active user"
  == render partial: 'users/active', collection: users.active(@period), as: :user
.inactive-people
  span.meta = pluralize users.inactive(@period).count, "inactive user"
  == render partial: 'users/inactive', collection: users.inactive(@period), as: :user

app/views/statuses/daily.html.slim
.container
  h2 Status updates for #{current_user.team.name} on #{@date.strftime("%Y/%m/%d")}
  .navigation
    span.prev
      => link_to '<< Previous day', daily_statuses_path(@prev.year, @prev.month, @prev.day), title: @prev.strftime("%Y/%m/%d")
    span.next
      = link_to 'Next day >>', daily_statuses_path(@next.year, @next.month, @next.day), title: @next.strftime("%Y/%m/%d")
  == render 'users'
  == render statuses
  = paginate statuses

app/views/statuses/edit.html.slim
.container
  h1 Editing status

  == render 'form'

  = link_to 'Back', :back

app/views/statuses/monthly.html.slim
.container
  h2 Status updates for #{current_user.team.name} on #{@date.strftime("%B %Y")}
  .navigation
    span.prev
      => link_to '<< Previous month', monthly_statuses_path(@prev.year, @prev.month), title: @prev.strftime("%Y/%m")
    span.next
      = link_to 'Next month >>', monthly_statuses_path(@next.year, @next.month), title: @next.strftime("%Y/%m")
  == render 'users'
  == render statuses
  = paginate statuses

app/views/statuses/new.html.slim
.container
  h1 New status
  == render 'form'

app/views/statuses/search.html.slim
.container
  == render @statuses
  = paginate @statuses

app/views/statuses/show.html.slim
== render @status

= link_to 'Edit', edit_status_path(@status)
'|
= link_to 'Back', statuses_path

app/views/statuses/today.html.slim
.container
  h2 Today's status updates for #{current_user.team.name}
  == render 'users'
  == render statuses
  = paginate statuses

app/views/statuses/yearly.html.slim
.container
  h2 Status updates for #{current_user.team.name} on #{@date.strftime("%Y")}
  .navigation
    span.prev
      = link_to '<< Previous year', yearly_statuses_path(@prev.year), title: @prev.year
    span.next
      = link_to 'Next year >>', yearly_statuses_path(@next.year), title: @next.year
  == render 'users'
  == render statuses
  = paginate statuses

app/views/statuses/yesterday.html.slim
.container
  h2 Yesterday's status updates for #{current_user.team.name}
  == render 'users'
  == render statuses
  = paginate statuses