config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resource :team, only: [:show, :update, :edit]

  resources :users, only: [:index, :show, :update] do
    # get :statuses, on: :member
  end

  resources :hashtags, only: [:index, :show] do
    # get :statuses, on: :member
    resource :like, only: [:create, :destroy]
  end

  resources :statuses, except: [:show] do
    collection do
      get :today
      get :yesterday
      constraints year: /\d{4}/, month: /(0?[1-9]|1[012])/, day: /(0?[1-9]|[12]\d|3[01])/ do
        get "/:year/:month/:day", action: :daily, as: :daily
        get "/:year/:month", action: :monthly, as: :monthly
        get "/:year", action: :yearly, as: :yearly
      end
    end
    resource :like, only: [:create, :destroy]
  end
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      - if user_signed_in?
        ul.nav.navbar-nav
          li = link_to 'Status', new_status_path
          li = link_to 'Users', users_path
          li = link_to 'Hashtags', hashtags_path
        ul.navbar-form.navbar-left
          == render 'layouts/search_form'
        ul.nav.navbar-nav.navbar-right
          li = link_to 'My team', team_path
          li = link_to 'Edit account', edit_user_registration_path
          li = link_to 'Sign out', destroy_user_session_path, method: 'delete'
      - else
        ul.nav.navbar-nav
          li = link_to 'Sign in', new_user_session_path
          li = link_to 'Sign up', new_user_registration_path

app/views/layouts/_search_form.html.slim
= form_tag search_path, method: "get", class: "form-search"  do
  .input-append
    = text_field_tag :query, params[:query], class: "form-control typeahead search-input", id: "search_input"
    = submit_tag "Search", name: nil, class: "btn btn-primary"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Crossroads'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Crossroads'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.10.5/typeahead.bundle.js"
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield